update build hooks, use buildx, English-only build

diff --git a/hooks/env b/hooks/env
--- a/hooks/env
+++ b/hooks/env
@@ -1,24 +1,24 @@
 #! /usr/bin/env bash
-# shellcheck disable=SC2034
+# shellcheck shell=bash disable=SC2034
 
 MANIFEST_TOOL_REPO="estesp/manifest-tool"
-MUSL_WHEEL_REPO="moonbuggy2000/python-musl-wheels"
+WHEEL_REPO="${WHEEL_REPO:-moonbuggy2000/python-alpine-wheels}"
 
 DATA_DIR='.build_data'
 QEMU_DIR='.qemu_static'
 IMPORTS_DIR='.imports'
 
 ARCH_YAML='arch.yaml'
-CONFIG_YAML="${DATA_DIR}/config.${DOCKER_TAG}.yaml"
+CONFIG_YAML="${DATA_DIR}/config.${DOCKER_TAG}${CONFIG_SUFFIX}.yaml"
 
 #BUILD_PLATFORM_ARG='true'
 
 # 1 day
 #CACHE_EXPIRY=86400
 # 7 days
-#CACHE_EXPIRY=604800
+CACHE_EXPIRY=604800
 # 30 days
-CACHE_EXPIRY=2592000
+#CACHE_EXPIRY=2592000
 
 DOCKER_FILE='Dockerfile'
 
@@ -28,20 +28,50 @@ DOCKER_FILE='Dockerfile'
 . "build.conf" || { echo 'No build.conf!'; exit 1; }
 
 ## handling writing and printing of parameters
-#	del_param       <key>
-#	add_param       <value> <key>
+#	del_param       <param>
+#	add_param       <value> <param>
 #	print_param     <value> <desc>
-#	add_print_param <value> <key> <desc>
+#	add_print_param <value> <param> <desc>
 del_param() { sed "/${1}/d" -i "${CONFIG_YAML}"; }
 add_param () {
-	key="${2}"
+	local value
 	value="$(echo "${1}" | xargs)"
-	del_param "${key}"
-	echo "${key}: ${value}" >> "${CONFIG_YAML}"
-	declare -g "${key}=${value}"
+	del_param "${2}"
+	echo "${2}: ${value}" >> "${CONFIG_YAML}"
+	declare -g "${2}=${value}"
 }
-print_param () { printf '%-20s %-8s\n' "${2}" "${1}"; }
+print_param () { printf '%-40s %-8s\n' "${2}" "${1}"; }
 add_print_param () { add_param "${1}" "${2}"; print_param "${1}" "${3:-${2}}"; }
+
+# only execute code to determine the parameter if it's unset, otherwise use the
+# existing set value
+#
+# these have arguments in different positions than the add/print_param functions
+#
+#	eval_param_if       <param> <command>
+#	eval_print_param_if <param> <desc> <command>
+eval_param_if () {
+	local param
+	local command
+	local value
+
+	param="${1}"
+	IFS=' ' read -a command <<< "${2}"
+
+	[ -z "${!param}" ] \
+		&& value="$(eval "${command[*]}")" \
+		|| value="${!param}"
+
+	add_param "${value}" "${param}"
+}
+
+eval_print_param_if () {
+	local desc
+	[ ! -z "${3}" ] && desc="${2}"
+
+	eval_param_if "${1}" "${3:-${2}}"
+	print_param "${!1}" "${desc:-${1}}"
+}
 
 ## curl the provided URL, handle errors and cache
 # get_url <URL>
@@ -52,16 +82,16 @@ get_url () {
 	cache_file="${DATA_DIR}/$(echo "${1}" | md5sum | cut -d' ' -f1)"
 
 	if [ -f "${cache_file}" ] && [ "$(( $(date +"%s") - $(date -r "${cache_file}" +"%s") ))" -lt "${CACHE_EXPIRY}" ]; then
-#		>&2 echo "Using cache: ${cache_file}"
 		cat "${cache_file}"
 	else
-#		>&2 echo "Downloading: ${1}"
 		page_data="$(curl -sL -w "%{http_code}\n" "${1}")"
 		http_code="${page_data:(-3)}"
 		if [ "${http_code}" = "200" ]; then
 			echo "${page_data%???}" | tee "${cache_file}"
 		else
-			echo "HTTP Error: ${http_code}"
+			>&2 echo "URL: ${1}"
+			>&2 echo "cache file: $(echo "${1}" | md5sum | cut -d' ' -f1)"
+			>&2 echo "HTTP Error: ${http_code}"
 			return 1
 		fi
 	fi
@@ -70,21 +100,25 @@ get_url () {
 # git_api_data <repo> <request>
 git_api_data () {	get_url "https://api.github.com/repos/${1}/${2}"; }
 
-# git_api_element <repo> <request> <tag>
+# git_api_element <repo> <request> <element>
 git_api_element () { git_api_data "${1}" "${2}" | sed -En 's|.*"'"${3}"'"\W+"([^"]+)".*|\1|p'; }
 
-# git_latest_release <repo> <tag_name>
+# git_latest_release <repo> (<element>)
 git_latest_release () { git_api_element "${1}" 'releases/latest' "${2:-tag_name}"; }
+
+# git_latest_tag <repo> (<element>)
+git_latest_tag () {	git_api_element "${1}" 'tags' "${2:-name}" | sort -uV | tail -n1; }
 
 # alpine_package_version <package> <alpine version> <repos>
 #
 # <repos> is a list, defaults to "main community"
 #
 alpine_package_version () {
+	local alpine_version
 	alpine_version="$(echo "${2}" | awk -F \. '{print $1"."$2}')"
-	repos="${3:-main community}"
+	local repos && repos="${3:-main community}"
 
-	packages=''
+	local package && packages=''
 	for repo in ${repos}; do
 		packages="$(printf '%s\n%s' \
 			"$(get_url "https://dl-cdn.alpinelinux.org/alpine/v${alpine_version}/${repo}/x86_64/" | grep -oP "^<a.*>\K[^<]*apk(?=<)")" \
@@ -98,14 +132,34 @@ alpine_package_version () {
 	echo "${packages}" | grep -oP "^${1}-\K[0-9.]*"
 }
 
+# debian_package_version <package> <debian release>
+#
+debian_package_version () {
+	local package && package="${1}"
+	local debian_release && debian_release="${2}"
+
+	if [ -z "${package}" ] || [ -z "${debian_release}" ]; then
+		return
+	fi
+
+	# either of these works
+#	package_version="$(get_url "https://sources.debian.org/api/src/${package}/" | grep -oP "\"suites\"[^}]*${debian_release}\"[^}]*version\D*\K[0-9\.\-]*")"
+	package_version="$(get_url "https://sources.debian.org/api/src/nginx/${debian_release}/" | grep -oP 'version"\:"\K([^\"]*)' | cut -d'+' -f1)"
+
+	echo "${package_version}"
+}
+
 # pypi_api_XXXX <project>
 pypi_api_data () {	get_url "https://pypi.org/simple/${1}"; }
 pypi_api_versions () { pypi_api_data "${1}" | grep -oP "(?<=${1}-)[0-9.]{4,}(?=.tar.gz)" | sort -uV; }
 pypi_api_latest_version () { pypi_api_versions "${1}" | tail -n1; }
 
 # py_musl_wheel_XXXX <wheel string>
-py_musl_wheel_versions () { docker_api_repo_tags "${MUSL_WHEEL_REPO}" | grep -oP "${1}\K([0-9.]+)(?=-py)" | sort -uV; }
+py_musl_wheel_versions () { docker_api_repo_tags "${WHEEL_REPO}" | grep -oP "${1}\K([0-9.]+)(?=-py)" | sort -uV; }
 py_musl_wheel_latest () { py_musl_wheel_versions "${1}" | tail -n1; }
+
+parse_version_major () { echo "${1}" | awk -F \. '{print $1}'; }
+parse_version_minor () { echo "${1}" | awk -F \. '{print $1"."$2}'; }
 
 #
 # py_requireed_vesion() and python_get_module_from_string() needs a refactor,
@@ -150,7 +204,7 @@ py_required_version () {
 	esac
 
 	[ -n "${requirements}" ] \
-		&& modstring="$(echo "${requirements}" | xargs -n1 | grep -P "^#?${modname}\W")" \
+		&& modstring="$(echo "${requirements}" | xargs -n1 | grep -P "^${modname}\W")" \
 		&& modsign="$(echo "${modstring}" | grep -oP "([<>=])(?==)")"
 
 	[ -n "${modsign}" ] && [ "x${modsign}" = "x>" ] \
@@ -169,7 +223,7 @@ py_required_version () {
 	echo "${modver}"
 }
 
-# take a string that includes some or all elements of the wheel iamge tag pattern
+# take a string that includes some or all elements of the wheel image tag pattern
 # and parse it to see if we can it to return a module name+version string
 #
 # wheel tag pattern: <module>(-<ssl_library)<mod_version>-py<py_version>-<arch>
@@ -180,9 +234,10 @@ python_get_module_from_string () {
 	local mod_longname
 	local mod_name
 	local mod_ver
-#	local mod_ssllib
 	local mod_pyver
 
+	# some python modules have a hyphen in the name so we can't simply split the
+	# string at hyphens, need to iterate and parse each fragment
 	IFS='-' read -r -a input_array <<< "${1}"
 
 	mod_namever=''
@@ -196,22 +251,20 @@ python_get_module_from_string () {
 			amd64|arm64v8|armv6|armv7|386|ppc64le|s390x)
 				break
 				;;
-			*[0-9])
-				mod_ver="${value//[[:alpha:]]/}"
-				;;&
 			*)
 				mod_namever="${mod_namever}-${value}"
 				;;
 		esac
 	done
 
-	mod_namever="${mod_namever/#-/}"
-	mod_longname="${mod_namever%%[0-9.]*}"
-	mod_longname="${mod_longname%-}"
+	# strip leading hyphen
+	mod_namever="${mod_namever:1}"
+
+	# strip trailing version number, don't strip integers that are part of the name
+	mod_longname="$(echo ${mod_namever} | sed -E 's|([0-9.]*)$||')"
 
 	case "${mod_longname##*-}" in
 		libressl|openssl)
-#			mod_ssllib="${mod_longname##*-}"
 			mod_name="${mod_longname%-*}"
 			;;
 		*)
@@ -219,8 +272,14 @@ python_get_module_from_string () {
 			;;
 	esac
 
-	[ -z "${mod_ver}" ] \
-		&& mod_ver="$(docker_api_repo_tags "${MUSL_WHEEL_REPO}" | \
+	# don't catch integers that may be part of the module name
+	mod_ver="$(echo ${mod_namever} | grep -oP '([0-9.]*)$')"
+
+	# by default, if no version is supplied, get the latest version from WHEEL_REPO
+	# if it exists in that repo and use PyPi if it doesn't
+	# set NO_WHEEL_REPO to use only PyPi
+	[ -z "${NO_WHEEL_REPO}" ] && [ -z "${mod_ver}" ] \
+		&& mod_ver="$(docker_api_repo_tags "${WHEEL_REPO}" | \
 			grep -oP "(?<=${mod_longname})[0-9.]+(?=-py${mod_pyver})" | sort -uV | tail -n1)"
 	[ -z "${mod_ver}" ] \
 		&& mod_ver="$(pypi_api_latest_version "${mod_name}")"
@@ -260,9 +319,10 @@ docker_api_latest () { docker_api_repo_tags "${1}" | grep '\.' | cut -d'-' -f1 |
 #	SOURCE_MAJOR=3; SOURCE_MAJOR_LATEST="$(search_repo_tags "${SOURCE_MAJOR}" "${REPO_TAGS}")"
 #	SOURCE_MINOR=3.5; SOURCE_MINOR_LATEST="$(search_repo_tags "${SOURCE_MINOR}" "${REPO_TAGS}")"
 search_repo_tags () {
-	local repo_tags && repo_tags="${2:-${SOURCE_REPO_TAGS}}"
-#	[ -z "${repo_tags}" ] && repo_tags="${SOURCE_REPO_TAGS}"
-	echo "${repo_tags}" | xargs -n1 | sed -En 's/^('"${1}"'[0-9.]*).*/\1/p' | sort -uV | tail -n1
+	local pattern && pattern="${1}"
+	shift
+	local repo_tags && repo_tags="${*:-${SOURCE_REPO_TAGS}}"
+	echo "${repo_tags}" | xargs -n1 | sed -En 's/^('"${pattern}"'[0-9.]*).*/\1/p' | sort -uV | tail -n1
 }
 
 # docker_container_contents <repo:tag> <outpud folder> <tar args>
@@ -357,6 +417,66 @@ get_manifest_tool () {
 		chmod a+x "manifest-tool"
 		echo './manifest-tool'
 	fi
+}
+
+## delete a file silently
+delete_file() {
+	rm -rf "$@" >/dev/null 2>&1
+}
+
+## get an image manifest
+#
+# get_manifest '<repo>/<image>:<tag>'
+#
+# returns the filename for the cached manifest
+#
+get_manifest() {
+	local source_image && source_image="${1}"
+	local source_repo && source_repo="${source_image%:*}"
+
+	manifest_file="${DATA_DIR}/manifest.${source_repo//\//_}.${source_image##*:}"
+
+	if [ ! -f "${manifest_file}" ] || [ "$(( $(date +"%s") - $(date -r "${manifest_file}" +"%s") ))" -gt "${CACHE_EXPIRY}" ]; then
+		>&2 printf 'Fetching manifest: %s.. ' "${source_image}"
+
+		manifest_cmd=("$(get_manifest_tool)" 'inspect' "${source_image}")
+		# pretty_manifest_cmd="$(echo "${manifest_cmd[*]}" | sed -r -e "s/(--)/\\\ \n\t\1/g")"
+		# >&2 printf '\n--- manifest command ---\n%s\n' "${pretty_manifest_cmd}"
+
+		local error
+		error="$("${manifest_cmd[@]}" 2>&1 1>"${manifest_file}")";
+
+		# if there's an error try and determine the cause so we can decide whether to
+		# cache the failure by keeping the empty manifest file:
+		#		cache the failure if it's indicative of the image/tag not existing
+		#		don't cache transient failures
+		#
+		if [ -n "${error}" ]; then
+			local error_message
+			error_message="$(echo "${error}" | grep -oP '.*msg\=\"\K[^\"]*' | head -n1)"
+
+			case ${error_message} in
+				*"not found") >&2 echo 'tag not found' ;;
+				"pull access denied"*) >&2 echo 'image not found or no auth' ;;
+				*toomanyrequests*)
+					>&2 echo 'rate limited'
+					delete_file "${manifest_file}"
+					exit 1
+					;;
+				*)
+					>&2 printf 'unknown error:\n%s\n' "${error}"
+					delete_file "${manifest_file}"
+					exit 1
+					;;
+			esac
+			return 1
+		fi
+
+		>&2 echo
+	# else
+	# 	>&2 printf 'Using cached manifest: %s\n' "${manifest_file}"
+	fi
+	echo "${manifest_file}"
 }
 
 # ifFunc <func>
